### PR TITLE
🦏 → 🍷

### PR DESCRIPTION
**Pull request by larsrh**
Removes all remnants of Nashorn, replaces them with Graal.

(Edited: previously I wrote _GraalVM_ but it actually only depends on a particular JAR file and can run on any JVM 8+)

### CODE REVIEW

**Comment by joyheron** [comment]
what versions of Java can this library then be used? Would it still work for Java 8?

**Comment by larsrh** [comment]
It's tested (and works) on Java 8+.

**Comment by mvitz** [comment]
Thanks for your contribution.

This PR looks fine for me but I don’t like that it removes the Nashorn based Renderer. As long as this library is build with JDK 8 (which if asking me will continue for some more time) it doesn’t cost us much to maintain the Nashorn variant, too. Dropping Nashorn would break compatibility which I don’t intend to break.

Keeping Nashorn would lead to some thoughts about the Graal dependencies which don’t need to be pulled by users if they intend to use the Nashorn variant. This would either mean declaring these as optional by us and requiring that users define these by themself or providing a separate module (and therefore “maven” artifact) for graal.

**Comment by larsrh** [comment]
> As long as this library is build with JDK 8 (which if asking me will continue for some more time) it doesn’t cost us much to maintain the Nashorn variant, too.

It does cost us much, in my opinion. For starters, the error messages are wildly different, leading to code clones in the tests.

Since not much has happened since 0.1.0, users could just stay at that version if they want to keep Nashorn.

**Comment by mvitz** [comment]
I don't agree and I don't think the tests needs to be duplicated, too.

The current tests are not perfect because they rely on some `toString`-Magic of passed Java objects. Ideally the JS engine should not matter and both variants would lead to the same output.

Since 0.1.0 is already used in production I don't want to possibly support multiple branches right now if some errors occur and these projects are not ready to move to Graal at that moment.

**Comment by larsrh** [comment]
> Since 0.1.0 is already used in production I don't want to possibly support multiple branches right now if some errors occur and these projects are not ready to move to Graal at that moment.

What other reason would users have to upgrade a version if not to switch to Graal?

**Comment by FND** [comment]
I sympathize with Michaels concerns, but here's something I don't yet understand:

> I don’t like that it removes the Nashorn based Renderer. As long as this library is build with JDK 8 […] Dropping Nashorn would break compatibility which I don’t intend to break.

a) Are JDK 8 and Java 8 different things? (Please excuse my ignorance, as you have done so many times in the past.) I'm confused because Lars says Java 8 works fine with Graal.

b) How would replacing Nashorn with Graal break compatibility; isn't the engine supposed an implementation detail; I thought that was sort of the point of this library? (Of course I'm aware that Graal provides _additional_ features.)

**Comment by joyheron** [comment]
It actually would break compatibility, since the class name is different. So updating the version would result in compiler errors.

**Comment by FND** [comment]
That seems unfortunate: _If_ my (b) assumption above is correct, perhaps this is an opportunity to provide an agnostic abstraction here? I realize that doesn't resolve the conflict though, so I'll pipe down now.

**Comment by larsrh** [comment]
@FND Regarding your questions:

> a) Are JDK 8 and Java 8 different things? (Please excuse my ignorance, as you have done so many times in the past.) I'm confused because Lars says Java 8 works fine with Graal.

For the purpose of this library, there's no difference between "JDK 8" and "Java 8".

> b) How would replacing Nashorn with Graal break compatibility; isn't the engine supposed an implementation detail - I thought that was sort of the point of this library? (Of course I'm aware that Graal provides _additional_ features, notably ESNext support.)

What @joyheron said, but also it's not such a big deal. I'd rather keep the underlying engine in the class name than to pretend that Nashorn vs. Graal is an implementation detail (I don't think it is, because as you said Graal provides more JS features).

Furthermore, we're talking about possibly a hand full of call sites that need to be adapted. The interface is still the same, just a different class name.

**Comment by mvitz** [comment]
To not break clients too much the `ComplateRenderer` Interface exists which almost all places in complate java based libraries and applications rely on.
In normal circumstances only one place depends on the specific JS engine by constructing a chosen implementation (e.g. `NashornComplateRender` or `GraalComplateRenderer`. Therefore I don't see this as a problem.

In an ideal world the chosen JS engine is an implementation detail and does not matter to the user but in the world we are living these JS engines don't behave the same (which can be seen by the current tests). Therefore by keeping the used JS Engine in the classes name and by letting the user choose which engine to use the surprises are kept to a minimum.

Although semantic versioning would allow to break that much because we are currently in the 0.x versions this is not what I will do. My plan would be adding Graal and deprecating Nashorn in the next release and drop Nashorn in the near future after the Graal based implementation is a little bit more battle proved.

**Comment by joyheron** [comment]
@mvitz Do you think for now that it would be sufficient to just duplicate the tests that we have for each rendering engine?

I agree with you that it would be ideal to have some kind of testing abstraction, but I'm not sure how much work that would be and what specific benefit that we would get from doing so.

Thinking about this, I agree with @larsrh and @mvitz that if there _are_ differences between rendering engines (and there are here), that it the behavior for users is more predictable if we have separate implementing classes for doing so.

In the long run, I would prefer that we deprecate the Nashorn engine to minimize any support that we need to provide. But I can see the wisdom of the more conservative approach that @mvitz suggests for removing Nashorn from `complate-java`, since the Graal engine has not yet been tested in actual applications yet.

**Comment by mvitz** [comment]
My english seems to be bad ;-) Yes duplicating the tests (= keeping the old one for Nashorn and putting the version of this PR beneath for Graal) is totally fine for me and would be my go to route here.

What I meant by abstraction for tests was that there should be more realistic test cases that do render some more complex stuff. The current tests just pass single objects into a view and check that these are rendered (which normally means just invoking `toString` on these objects). This leads to small differences between the engines which hopefully should not be relevant for “real” use cases. Changes to the tests can be done after merging the addition of Graal and I would look if I can spare some time to do this.

**Comment by larsrh** [comment]
Sounds good. Will update the PR accordingly.

**Comment by larsrh** [comment]
This PR now contains only the addition of a GraalJS renderer. My Maven-fu is not good enough to split this up into a separate module, but maybe an optional dependency on the GraalJS JAR will suffice.

**Comment by mvitz** [comment]
I think for the time being we can live with shipping Graal by default and adding some documentation that the Graal implementation should be preferred. I will add this documentation later.

**Pull request merged**
